version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "update-ds-agents"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-sraswznf2zk7"
s3_prefix = "update-ds-agents"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Stage=\"prod\""
image_repositories = []
